export const carFormElements = {
  inputs: {
    carId: document.querySelector("#carId"),
    make: document.querySelector("#make"),
    model: document.querySelector("#model"),
    year: document.querySelector("#year"),
    dailyRate: document.querySelector("#dailyRate"),
    category: document.querySelector("#category"),
    color: document.querySelector("#color"),
    transmission: document.querySelector("#transmission"),
    fuelType: document.querySelector("#fuelType"),
    fuelCapacity: document.querySelector("#fuelCapacity"),
    luggageCapacity: document.querySelector("#luggageCapacity"),
    passengerCapacity: document.querySelector("#passengerCapacity"),
    rating: document.querySelector("#rating"),
    imageUrls: document.querySelector("#imageUrls"),
    modalHead: document.getElementById("carEditModalLabel"),
    confirmCarBtn: document.getElementById("confirmCarBtn"),
  },
  feedbacks: {
    make: document.querySelector("#make-feedback"),
    model: document.querySelector("#model-feedback"),
    year: document.querySelector("#year-feedback"),
    dailyRate: document.querySelector("#dailyRate-feedback"),
    category: document.querySelector("#category-feedback"),
    color: document.querySelector("#color-feedback"),
    transmission: document.querySelector("#transmission-feedback"),
    fuelType: document.querySelector("#fuelType-feedback"),
    fuelCapacity: document.querySelector("#fuelCapacity-feedback"),
    luggageCapacity: document.querySelector("#luggageCapacity-feedback"),
    passengerCapacity: document.querySelector("#passengerCapacity-feedback"),
    rating: document.querySelector("#rating-feedback"),
    imageUrls: document.querySelector("#imageUrls-feedback"),
  },
};
